### ISSUE TITLE
[Issue] - "Advanced Cutting" works wrong

### ISSUE THREAD

**Issue by Lirk88** [bswebdk/FFQueue#25] opened 2023-08-07 21:50 UTC
Hi. Did you test "Advanced Cutting" option? I think it works wrong. For example, I set the following parameters: From: 00:00:05:00 To: 00:00:10.000; Quick cuts: Disabled. Generated command is:

-hide_banner -i "input.mp4" -map 0:0 -map 0:1 -filter_complex "[0:0]trim=5.000:10.000,setpts=PTS-STARTPTS[F1];[0:1]atrim=5.000:10.000,asetpts=PTS-STARTPTS[F2];[F1][F2]concat=n=1:v=1:a=1[F3][F4];[F3]trim=5.000:10.000,setpts=PTS-STARTPTS[F5];[F4]atrim=5.000:10.000,asetpts=PTS-STARTPTS[F6];[F5][F6]concat=n=1:v=1:a=1[F7][F8];[F7]copy;[F8]acopy" -c:v libx264 -b:v 1000k -c:a libmp3lame -b:a 128k -y "output.mp4" 

"-map 0:0 -map 0:1" -wrong options in this case, because it processing full time of the file and generated command has to many strange copied parameters. Output file has four streams: two videos and two audios (cutted and uncutted).

In this case right variant is: ffmpeg -hide_banner -i "input.mp4" -filter_complex "[0:0]trim=5.000:10.000,setpts=PTS-STARTPTS[F1];[0:1]atrim=5.000:10.000,asetpts=PTS-STARTPTS[F2];[F1][F2]concat=n=1:v=1:a=1" -c:v libx264 -b:v 1000k -c:a libmp3lame -b:a 128k -y "out.mp4" 

With two time spans: From: 00:00:05:00 To: 00:00:10.000; From: 00:00:15:00 To: 00:00:20.000; Quick cuts: Disabled. Generated command is:

-hide_banner -i "input.mp4" -map 0:0 -map 0:1 -filter_complex "[0:0]trim=5.000:10.000,setpts=PTS-STARTPTS[F1];[0:0]trim=15.000:20.000,setpts=PTS-STARTPTS[F2];[0:1]atrim=5.000:10.000,asetpts=PTS-STARTPTS[F3];[0:1]atrim=15.000:20.000,asetpts=PTS-STARTPTS[F4];[F1][F3][F2][F4]concat=n=2:v=1:a=1[F5][F6];[F5]copy;[F6]acopy" -c:v libx264 -b:v 1000k -c:a libmp3lame -b:a 128k -y "output.mp4"

And here also the same problem due to "-map 0:0 -map 0:1" interfering options, but without it works properly. Anyway is better to use -map 0:v -map 0:a -map 0:s... instead stream numbers.

**Comment by bswebdk** [comment] 2023-08-08 17:40
Thank you for the information! In your first filtergraph, what comes after "[F3][F4];" should be "[F3]copy;[F4]acopy" and no more after that but instead a new set of trim filters are added. So, the first trim filter is never terminated properly which is why you get that odd result. Annoyingly I cannot tell you why and how that erroneous command has been produced.

I have just tested Adv. Cuts again with 3 different sources and I am unable to reproduce the problem; All 3 sources where perfectly trimmed as requested. The last command you provide (with two cuts) is correct, I have tested it and it works as expected with 3 different sources.

**Comment by Lirk88** [comment] 2023-08-19 18:50
> I have just tested Adv. Cuts again with 3 different sources and I am unable to reproduce the problem; All 3 sources where perfectly trimmed as requested. The last command you provide (with two cuts) is correct, I have tested it and it works as expected with 3 different sources.

The first problem appears when I use **one** time span. The Second problem - look streams in output file with Mediainfo.

**Comment by bswebdk** [comment] 2023-08-20 11:10
I have checked it again, and the issue can be confirmed when selecting to "Keep" the selected parts. The issue is fixed in the next release. Thank you very much for the appreciated information! :-)

**Comment by bswebdk** [comment] 2023-08-26 11:44
Issue resolved in V1.7.62.

**Closed as completed by bswebdk** 2023-08-26 11:44 UTC
