### ISSUE TITLE
Demuxing THD results in loop and forced termination on Linux

### ISSUE THREAD

**Issue by sfatula** [bswebdk/FFQueue#9] opened 2020-01-22 00:12 UTC
I have this preset:

`[preset]
id=AWfGxW8BAACsQVl0n9wVIg==
name=Demux TrueHD
video_codec=copy
video_rate=1000,1,,,
key_frames=,,,0,40,0,0,0
hw_decode=,,,
video_quality=0,75,0,75,0,50,0,90,0,40,0,10
audio_codec=copy
audio_rate=128,1,,,
audio_quality=0,80
output_format=truehd
finger_print=6Ctpx8WgFj0HIVLjhhHlkEYM+As=
segmenting=0,0,0,0,0,0,0`

So, input is a mkv with truehd audio in it, and, I select only the truehd track. I specify an output file of whatever.thd. I select the above preset. Click start, and, unlike other jobs, I do not get a progress report. I do get the correct thd file, however, FFQueue keeps running and using 100% cpu. Eventually linux says he app is not responding, and, it is force quit. 

I have not had the issue on anything else, just on this 1 truehd use.

**Comment by bswebdk** [comment] 2020-01-23 11:29
Please try to right-click the job in the list and select "Show command(s)". From the console in the bottom of FFQueue, copy that command and try to execute it in a terminal (remember to prefix "/path/to/ffmpeg ") and see what happens.

My guess is that the status output from ffmpeg is not understood by FFQueue. I have no TrueHD files to test with, but I'll keep it in mind :-)

**Comment by sfatula** [comment] 2020-01-24 19:56
Ok, here's the log. Note, it actually works despite those warnings. That is, the extracted audio works fine, and, the demux works fine. The program merely goes into a loop. Perhaps you can prevent the loop part. I've seen a few FFMPEG bug reports, many are different though. Might just be the framerate as it's showing wrong in the mkv. Using other tools like gMKVExtractGUI, no issues. Output is identical. 
[ffqueue.zip](https://github.com/bswebdk/FFQueue/files/4110416/ffqueue.zip)

I also noticed, when I had 3 inputs in a job, it also goes into a loop. But that also works.

**Comment by bswebdk** [comment] 2020-01-26 11:34
Thank you for taking the time to make a log and post it! I have looked at it, it is ~170MiB of errors related to either FFmpeg or the TrueHD codec. Since these messages are not marked as errors, FFQueue cannot correctly ignore them and this may cause excessive memory usage which again causes FFQueue to either slow down or completely lock up. I will try to figure out a sollution - but I cannot promise anything. I think you should post the log to the FFmpeg developers and see what they have to say about it: https://github.com/FFmpeg/FFmpeg

**Comment by bswebdk** [comment] 2020-08-17 13:53
I'm closing this issue, I cannot reproduce it and it is not a bug in FFQueue.

**Closed as completed by bswebdk** 2020-08-17 13:53 UTC
